/* ════════════════════════════════════════════════
   dict.ts — 대시보드(쇼핑몰 관리) 한글 → 영어 사전
   런타임 번역 레이어(DashTranslator)가 영어 모드일 때
   화면의 한글 텍스트를 이 사전으로 치환한다.
   · 키 = 화면에 그대로 보이는 한글(트림 기준 정확 일치)
   · 사전에 없으면 한글 그대로 둠(안 깨짐) → 점진적으로 채운다
════════════════════════════════════════════════ */
export const DICT: Record<string, string> = {
  // ── 사이드바 / 네비 ──
  "대시보드": "Dashboard",
  "쇼핑몰": "Stores",
  "상품": "Products",
  "주문": "Orders",
  "고객": "Customers",
  "리뷰": "Reviews",
  "문의": "Inquiries",
  "재입고": "Restock",
  "알림": "Notifications",
  "분석": "Analytics",
  "요금제": "Pricing",
  "계정 설정": "Account Settings",
  "설정": "Settings",
  "BUILD": "BUILD",
  "OPERATE": "OPERATE",
  "SYSTEM": "SYSTEM",
  "관리": "Manage",
  "메뉴": "Menu",
  "로그아웃": "Log out",
  "로그인": "Log in",
  "회원가입": "Sign up",
  "무료로 시작": "Start free",
  "최고관리자": "Super Admin",
  "온라인": "Online",
  "창업자": "Founder",
  "👑 플랫폼 관리자": "👑 Platform Admin",
  "🏪 창업자": "🏪 Founder",
  "👑 운영자 시크릿 보기": "👑 Admin secret view",
  "← 운영자로 나가기": "← Exit to admin",
  "비로그인 (둘러보기)": "Not logged in (browsing)",
  "📅 이용 기간": "📅 Subscription period",
  "사용 기간 만료": "Subscription expired",
  "연장 문의가 필요해요": "Renewal inquiry needed",

  // ── 공통 버튼/동작 ──
  "저장": "Save",
  "저장하기": "Save",
  "취소": "Cancel",
  "삭제": "Delete",
  "수정": "Edit",
  "편집": "Edit",
  "추가": "Add",
  "닫기": "Close",
  "확인": "Confirm",
  "적용": "Apply",
  "적용하기": "Apply",
  "등록": "Register",
  "등록하기": "Register",
  "생성": "Create",
  "생성하기": "Create",
  "변경": "Change",
  "초기화": "Reset",
  "복사": "Copy",
  "복사됨": "Copied",
  "미리보기": "Preview",
  "더보기": "More",
  "전체": "All",
  "검색": "Search",
  "필터": "Filter",
  "정렬": "Sort",
  "다운로드": "Download",
  "업로드": "Upload",
  "이전": "Previous",
  "다음": "Next",
  "처음으로": "Home",
  "뒤로": "Back",

  // ── 대시보드 개요 ──
  "오늘 매출": "Today's Sales",
  "이번 달 매출": "This Month's Sales",
  "총 주문": "Total Orders",
  "신규 주문": "New Orders",
  "총 매출": "Total Sales",
  "방문자": "Visitors",
  "상품 수": "Products",
  "고객 수": "Customers",
  "최근 주문": "Recent Orders",
  "주문이 없어요": "No orders yet",
  "환영합니다": "Welcome",
  "빠른 시작": "Quick Start",
  "쇼핑몰 만들기": "Create a store",
  "상품 등록": "Add a product",

  // ── 상품 ──
  "상품 관리": "Product Management",
  "상품 추가": "Add Product",
  "새 상품": "New Product",
  "상품명": "Product Name",
  "가격": "Price",
  "정가": "List Price",
  "할인가": "Sale Price",
  "재고": "Stock",
  "카테고리": "Category",
  "상품 설명": "Product Description",
  "이미지": "Image",
  "대표 이미지": "Main Image",
  "옵션": "Options",
  "품절": "Sold Out",
  "판매중": "On Sale",
  "숨김": "Hidden",
  "진열": "Display",
  "상품이 없어요": "No products yet",
  "첫 상품을 등록해 보세요": "Add your first product",

  // ── 주문 ──
  "주문 관리": "Order Management",
  "주문번호": "Order No.",
  "주문일": "Order Date",
  "주문자": "Customer",
  "주문 상태": "Order Status",
  "결제금액": "Total",
  "배송지": "Shipping Address",
  "송장번호": "Tracking No.",
  "신규": "New",
  "처리중": "Processing",
  "배송중": "Shipping",
  "배송완료": "Delivered",
  "완료": "Completed",
  "환불": "Refunded",
  "주문이 들어오면 여기에 표시돼요": "Orders will appear here",

  // ── 고객 ──
  "고객 관리": "Customer Management",
  "이름": "Name",
  "이메일": "Email",
  "전화번호": "Phone",
  "가입일": "Joined",
  "총 구매액": "Total Spent",
  "등급": "Grade",
  "적립금": "Points",
  "회원": "Member",
  "고객이 없어요": "No customers yet",

  // ── 설정 / 계정 ──
  "계정 정보": "Account Info",
  "비밀번호": "Password",
  "비밀번호 변경": "Change Password",
  "현재 비밀번호": "Current Password",
  "새 비밀번호": "New Password",
  "비밀번호 확인": "Confirm Password",
  "저장되었습니다": "Saved",
  "변경되었습니다": "Changed",
  "회원 탈퇴": "Delete Account",

  // ── 요금제(보강) ──
  "현재 플랜": "Current Plan",
  "무제한": "Unlimited",
  "무료": "Free",
  "업그레이드": "Upgrade",
  "업그레이드 문의": "Upgrade",

  // ── 상태/공통 메시지 ──
  "로딩 중...": "Loading...",
  "불러오는 중...": "Loading...",
  "저장 중...": "Saving...",
  "처리 중...": "Processing...",
  "오류가 발생했어요": "An error occurred",
  "다시 시도해 주세요": "Please try again",
  "준비 중인 기능이에요": "Coming soon",
  "필수 입력이에요": "Required",
  "필수": "Required",
  "선택": "Optional",
  "사용함": "Enabled",
  "사용 안 함": "Disabled",
  "켜기": "On",
  "끄기": "Off",
  "예": "Yes",
  "아니오": "No",

  // ── 대시보드 개요 (page) ──
  "내 쇼핑몰": "My Stores",
  "현황 통계": "Overview",
  "사용 가능 스킨": "Available Skins",
  "운영 쇼핑몰": "Active Stores",
  "전체 상품": "Total Products",
  "전체 상품 보기": "View all products",
  "빠른 작업": "Quick Actions",
  "스튜디오에서 스킨 고르고 생성": "Pick a skin in Studio and create",
  "최근 쇼핑몰": "Recent Stores",
  "만든 매장 목록·관리": "Your stores",
  "모든 쇼핑몰을 여기서 만들고 · 수정하고 · 관리하세요": "Create, edit and manage all your stores here",
  "주소 (수정 가능)": "Address (editable)",
  "🧾 새 주문 (신규)": "🧾 New Orders",
  "📦 전체 주문": "📦 Total Orders",
  "💰 총 매출 (취소 제외)": "💰 Total Sales (excl. cancelled)",
  "구독 사용 기간": "Subscription period",
  "일 남음": "days left",
  "까지": "until",

  // ── 주문 페이지 ──
  "🧾 주문": "🧾 Orders",
  "고객 주문을 한 곳에서 확인하고 상태를 관리하세요.": "View and manage all customer orders in one place.",
  "새 주문": "New Orders",
  "전체 주문": "Total Orders",
  "아직 주문이 없어요": "No orders yet",
  "주문 금액(취소 제외)": "Revenue (excl. cancelled)",
  "배송비": "Shipping",
  " (배송비 포함)": " (incl. shipping)",
  "(배송비 포함)": "(incl. shipping)",

  // ── 고객 페이지 ──
  "👤 고객": "👤 Customers",
  "💰 회원 적립금": "💰 Member Points",
  "주문한 고객을 한눈에 보고, 단골을 찾아보세요.": "See who ordered and find your regulars.",
  "전체 고객": "Total Customers",
  "재구매 고객": "Repeat Customers",
  "누적 구매액": "Total Spent",
  "구매액": "Spent",
  "연락처": "Contact",
  "최근": "Recent",
  "아직 고객이 없어요": "No customers yet",

  // ── 설정 페이지 ──
  "관리자 · 컨트롤타워": "Admin · Control Tower",
  "관리자 계정": "Admin Account",
  "관리자 계정과 비밀번호를 관리하세요": "Manage your admin account and password",
  "관리자 로그인": "Admin Login",
  "비밀번호를 바꾸려면 먼저 로그인하세요.": "Log in first to change your password.",
  "로그인한 관리자 계정의 비밀번호를 바꿉니다.": "Change the password for the logged-in admin account.",
  "새 비밀번호 확인": "Confirm New Password",
  "🔒 계정 보안 팁": "🔒 Account Security Tips",
  "💬 도움이 필요하세요?": "💬 Need help?",
  "⚡ 빠른 이동": "⚡ Quick Links",
  "📈 분석": "📈 Analytics",
  "🏬 쇼핑몰": "🏬 Stores",
  "💎 요금제": "💎 Pricing",
  "온봇": "OnBot",
  "요금제 페이지": "Pricing page",
  "6자 이상": "6+ characters",
  "8자 이상": "8+ characters",
  "다시 입력": "Re-enter",
  "같은 비밀번호": "Same password",

  // ── 몰 관리 (dashboard/[id]) 섹션 ──
  "🔎 검색 노출 (SEO)": "🔎 Search Visibility (SEO)",
  "💳 결제 설정": "💳 Payment Settings",
  "🌐 내 도메인 연결": "🌐 Connect My Domain",
  "🧩 대문 구성": "🧩 Homepage Layout",
  "🎨 디자인": "🎨 Design",
  "🚚 배송비": "🚚 Shipping Fee",
  "🎨 상단 꾸미기": "🎨 Header Styling",
  "📦 상품": "📦 Products",
  "🗣️ 손님 후기·문의": "🗣️ Reviews & Inquiries",
  "💬 쇼핑몰 챗봇 (자주 묻는 질문)": "💬 Store Chatbot (FAQ)",
  "🎉 이벤트 팝업·띠배너": "🎉 Event Popup & Banner",
  "💰 적립금": "💰 Points",
  "🏷️ 카테고리": "🏷️ Categories",
  "🎟️ 쿠폰": "🎟️ Coupons",
  "💎 회원 등급": "💎 Member Grades",
  "⭐ 구매 후기 (리뷰)": "⭐ Reviews",
  "💬 상품 문의 (Q&A)": "💬 Product Q&A",
  "🏢 사업자 정보": "🏢 Business Info",
  "💳 카드결제 연결 (PG)": "💳 Card Payment (PG)",
  "🟢 발행됨": "🟢 Published",
  "🚀 발행하기": "🚀 Publish",
  "⚪ 비공개": "⚪ Private",
  "비공개로 전환": "Switch to Private",
  "발행해야 고객에게 보입니다": "Must publish to be visible to customers",
  "고객이 접속할 수 있어요": "Customers can access it",
  "👑 운영자 모드 — 다른 회원의 쇼핑몰을 관리 중입니다. 변경 시 즉시 적용돼요.": "👑 Admin mode — managing another member's store. Changes apply immediately.",
  "결제 설정 저장": "Save Payment Settings",
  "배송비 설정 저장": "Save Shipping Settings",
  "사업자 정보 저장": "Save Business Info",
  "이벤트 설정 저장": "Save Event Settings",
  "적립금 설정 저장": "Save Points Settings",
  "챗봇 설정 저장": "Save Chatbot Settings",
  "고객 주문 관리": "Customer Order Management",
  "고객센터 전화": "Support Phone",
  "대표자명": "Representative",
  "사업자등록번호": "Business Reg. No.",
  "상호 (상점·법인명)": "Business Name",
  "내 도메인(mybrand.com)을 이 쇼핑몰에 연결할 수 있어요.": "Connect your own domain (mybrand.com) to this store.",
  "누적 구매액에 따라 VIP 등급을 나누고 등급별 할인을 줄 수 있어요.": "Split VIP grades by total spend and give per-grade discounts.",
  "주문 완료 시 손님에게 적립금을 쌓아 단골을 만들 수 있어요.": "Give points on completed orders to build loyal customers.",

  // ── 상품 폼 (ProductForm) ──
  "🔍 미리보기 · 실시간": "🔍 Preview · Live",
  "가격(원) *": "Price (KRW) *",
  "상품명 *": "Product Name *",
  "상품명이 여기에 표시돼요": "Product name shows here",
  "상품 사진 (선택 — 없으면 이모지 사용)": "Product Photo (optional — emoji if none)",
  "옵션 (색상·사이즈 등)": "Options (color, size, etc.)",
  "이모지(사진 없을 때 대체)": "Emoji (fallback when no photo)",
  "재고 수량(비우면 무제한)": "Stock (blank = unlimited)",
  "정가 (할인 전 가격·선택)": "List Price (before discount, optional)",
  "태그(NEW·BEST 등)": "Tag (NEW, BEST, etc.)",
  "브랜드": "Brand",
  "설명": "Description",
  "리빙": "Living",
  "뷰티": "Beauty",
  "테크": "Tech",
  "패션": "Fashion",
  "액세서리": "Accessories",
  "식품": "Food",
  "농산물": "Produce",
  "수산물": "Seafood",
  "축산물": "Meat",
  "베이커리": "Bakery",
  "가공·반찬": "Processed",
  "베이직": "Basic",

  // ── 분석 페이지 ──
  "🏆 인기 상품 (실제 판매 수량)": "🏆 Top Products (units sold)",
  "🧾 주문 수": "🧾 Order Count",
  "📊 최근 14일 매출 추이": "📊 Sales (last 14 days)",
  "📦 판매 수량": "📦 Units Sold",
  "📊 평균 주문액": "📊 Avg Order Value",
  "매출 추이·상품별 판매·카테고리 분포 등 분석 리포트를 볼 수 있어요.": "View reports: sales trend, per-product sales, category mix, and more.",
  "매출·상품·고객 통계를 한눈에 볼 수 있어요.": "See sales, product, and customer stats at a glance.",
  "매출과 운영 현황을 한눈에": "Sales and operations at a glance",
  "데이터가 없어요.": "No data yet.",
  "스킨 분포": "Skin Distribution",
  "카테고리 분포": "Category Distribution",
  "합계": "Total",
  "아직 판매된 상품이 없어요. 주문이 들어오면 표시돼요.": "No products sold yet. They'll show when orders come in.",
  "최근 14일 매출이 없어요. 주문(완료/접수)이 들어오면 일별로 표시돼요.": "No sales in the last 14 days. Daily sales appear as orders come in.",

  // ── 플랫폼 관리 (platform) ──
  "🧾 새 주문": "🧾 New Orders",
  "💰 전체 거래액": "💰 Total Revenue",
  " (만료)": " (expired)",
  "모든 회원과 쇼핑몰·매출을 총괄하고 직접 제어합니다": "Oversee and control all members, stores, and sales",
  "역할": "Role",
  "이용 만료": "Expiry",
  "전체 관리": "Platform",
  "전체 쇼핑몰": "Total Stores",
  "전체 회원": "Total Members",

  // ── 매장 목록 (stores) ──
  "＋ 새 쇼핑몰 만들기": "＋ Create New Store",
  "매장을 만들고 관리하세요": "Create and manage your stores",

  // ── 쿠폰 (CouponManager) ──
  "🎟️ 새 쿠폰 발급": "🎟️ Issue New Coupon",
  "⚪ 비활성": "⚪ Inactive",
  "🟢 활성": "🟢 Active",
  "(원)": "(KRW)",
  "만료": "Expired",
  "발급 중…": "Issuing…",
  "발급에 실패했어요.": "Failed to issue.",
  "쿠폰 발급": "Issue Coupon",
  "한도 소진": "Limit reached",
  "금액(원) 할인": "Amount (KRW) off",
  "만료일 (비우면 무기한)": "Expiry (blank = no expiry)",
  "사용 한도 (비우면 무제한)": "Usage limit (blank = unlimited)",
  "아직 발급한 쿠폰이 없어요.": "No coupons issued yet.",
  "최소 주문금액 (원)": "Min. order (KRW)",
  "쿠폰 코드": "Coupon Code",
  "퍼센트(%) 할인": "Percent (%) off",
  "할인 종류": "Discount Type",

  // ── 회원 등급 (StoreGradeManager) ──
  "✨ 기본 등급 채우기 (일반·실버·골드·VIP)": "✨ Fill default grades (Basic·Silver·Gold·VIP)",
  "＋ 등급 추가": "＋ Add Grade",
  "등급 추가": "Add Grade",
  "기본 등급 채우기 실패": "Failed to fill default grades",
  "꺼짐 — 등급 미사용": "Off — grades disabled",
  "수정 실패": "Update failed",
  "추가 실패": "Add failed",
  "이 등급을 삭제할까요?": "Delete this grade?",
  "켜짐 — 구매액에 따라 등급 할인이 적용돼요": "On — grade discounts apply by total spend",
  "% 할인": "% off",
  "누적": "Total",
  "아직 등급이 없어요. 위에서 추가하거나 기본 등급을 채워보세요.": "No grades yet. Add one above or fill defaults.",

  // ── 적립금 (MemberPoints) ──
  "금액을 입력해 주세요.": "Please enter an amount.",
  "쿠폰을 선택해 주세요.": "Please select a coupon.",
  "쿠폰을 발급했어요 ✓ (회원 쿠폰함에 담김)": "Coupon issued ✓ (added to member's coupon box)",
  "사용": "Use",
  "실패": "Failed",
  "처리 실패": "Failed",
  "원": "KRW",
  "적립": "Earn",
  "지급": "Grant",
  "차감": "Deduct",
  "회수": "Revoke",
  "불러오는 중…": "Loading…",
  "아직 적립금 변동 내역이 없어요.": "No points history yet.",
  "적립금 내역": "Points History",
  "적립금 지급 / 차감": "Grant / Deduct Points",
  "쿠폰 선택…": "Select coupon…",

  // ── 배송비 (ShippingSettings) ──
  "기준액": "Threshold",
  "꺼짐 — 배송비 없이(무료) 받아요": "Off — free shipping (no fee)",
  "켜짐 — 주문 시 배송비가 더해져요": "On — shipping fee added at checkout",
  "기본 배송비": "Base Shipping Fee",
  "도서산간 추가 배송비": "Remote Area Surcharge",
  "무료배송": "Free Shipping",
  "무료배송 기준액": "Free Shipping Threshold",
  "주문마다 더해질 배송비예요.": "Shipping fee added to each order.",
  "제주·도서산간 주문이면 더 받을 금액 (0이면 안 받음).": "Extra for Jeju/remote areas (0 = none).",

  // ── 이벤트 팝업·배너 (PromoSettings) ──
  "📢 상단 띠배너": "📢 Top Banner",
  "🪟 진입 팝업": "🪟 Entry Popup",
  "꺼짐": "Off",
  "켜짐 — 대문 맨 위 얇은 줄에 표시": "On — shows as a thin bar at the top",
  "켜짐 — 손님 접속 시 가운데 모달로 표시": "On — shows as a center modal on visit",
  "글자색": "Text Color",
  "내용": "Content",
  "배경색": "Background Color",
  "배너 문구": "Banner Text",
  "버튼 링크": "Button Link",
  "버튼 문구 (선택)": "Button Text (optional)",
  "이미지 URL (선택)": "Image URL (optional)",
  "제목": "Title",
  "클릭 링크 (선택 · URL)": "Click Link (optional · URL)",

  // ── 리뷰 / 문의 / 재입고 / 알림 페이지 ──
  "⭐ 리뷰": "⭐ Reviews",
  "답글 단 리뷰": "Replied",
  "손님이 남긴 후기를 확인하고 답글을 달아보세요.": "Check customer reviews and reply to them.",
  "아직 리뷰가 없어요": "No reviews yet",
  "전체 리뷰": "Total Reviews",
  "평균 별점": "Avg Rating",
  "💬 상품 문의": "💬 Product Inquiries",
  "답변 대기": "Pending",
  "답변 완료": "Answered",
  "손님이 상품에 남긴 질문을 확인하고 답변을 달아보세요.": "Check and answer customer questions on products.",
  "아직 문의가 없어요": "No inquiries yet",
  "전체 문의": "Total Inquiries",
  "🔔 재입고 알림 신청": "🔔 Restock Alerts",
  "품절 상품에 손님의 재입고 알림을 받고, 입고되면 한 번에 알려줄 수 있어요.": "Collect restock requests on sold-out items and notify customers at once.",
  "로그인하면 신청 목록을 볼 수 있어요.": "Log in to see the request list.",
  "아직 재입고 신청이 없어요": "No restock requests yet",
  "알림 대기": "Awaiting",
  "전체 신청": "Total Requests",
  "🔔 알림": "🔔 Notifications",
  "새 주문·리뷰가 들어오면 여기에서 바로 확인하세요.": "Check new orders and reviews here as they arrive.",

  // ── 카테고리 / 옵션 ──
  "＋ 추가": "＋ Add",
  "아래로": "Down",
  "위로": "Up",
  "기존 상품 카테고리를 불러오는 중…": "Loading existing categories…",
  "꺼짐 — 상품 단위 재고 사용": "Off — stock by product",
  "켜짐 — 조합마다 재고 입력": "On — stock per combination",
  "선택지 삭제": "Delete choice",
  "0이면 품절": "0 = sold out",
  "조합마다 재고를 정하세요. ": "Set stock per combination. ",

  // ── 브랜딩 (BrandingForm) ──
  "로그인이 필요해요": "Login required",
  "상단·하단 꾸미기 저장": "Save Header/Footer",
  "엄선한 상품을 한 곳에. 지금 둘러보세요.": "Curated products in one place. Browse now.",
  "업로드 실패: ": "Upload failed: ",
  "업로드 중…": "Uploading…",
  "대문 문구": "Homepage Tagline",
  "대문 배너 이미지": "Homepage Banner Image",
  "대문 제목": "Homepage Title",
  "둘러보기": "Browse",
  "로고 (없으면 상호명 표시)": "Logo (shows business name if none)",

  // ── 도메인 연결 (DomainHelp) ──
  "🌐 내 도메인 연결하는 법": "🌐 How to Connect Your Domain",
  "📌 예시 ①: shop.mybrand.com 처럼 앞에 글자가 붙는 경우": "📌 Example 1: a subdomain like shop.mybrand.com",
  "📌 예시 ②: mybrand.com 처럼 그냥 도메인인 경우": "📌 Example 2: a bare domain like mybrand.com",
  "DNS 레코드 1줄 추가": "Add 1 DNS record",
  "도메인을 산 사이트에 로그인": "Log in where you bought the domain",
  "왼쪽 칸에 내 도메인 적고 저장": "Enter your domain on the left and save",
  "아래 표대로 한 줄을 추가하고 저장하세요.": "Add one row as in the table below and save.",
  "자동으로 처리": "Handled automatically",
  "몇 분~몇 시간": "A few minutes to a few hours",

  // ── 챗봇 (BotStylePicker) ──
  "꺼짐 — 챗봇 숨김": "Off — chatbot hidden",
  "켜짐 — 손님 화면 오른쪽 아래에 떠요": "On — shows at bottom-right for customers",
  "챗봇 모양 (스킨 분위기에 맞게 골라보세요)": "Chatbot Style (match your skin's vibe)",
  "챗봇 이름 (선택)": "Chatbot Name (optional)",
  "첫 인사말 (선택)": "Greeting (optional)",
  "비우면 기본 인사말이 나와요. 아래에서 질문/답을 추가해야 챗봇이 표시됩니다.": "Leave blank for the default greeting. Add Q&As below to show the chatbot.",

  // ── FAQ (StoreFaqManager) ──
  "기본 질문 채우기 실패": "Failed to fill default questions",
  "이 질문을 삭제할까요?": "Delete this question?",
  "새 질문/답 추가": "Add New Q&A",

  // ── 구독 제어 (SubscriptionControls) ──
  "📅 구독 사용 기간": "📅 Subscription Period",
  "💳 베이직 결제완료": "💳 Basic Paid",
  "💳 프로 결제완료": "💳 Pro Paid",
  "💳 프리미엄 결제완료": "💳 Premium Paid",
  "결제 완료 처리 (등급 + 오늘부터 1개월)": "Mark as paid (grade + 1 month from today)",
  "요금제 변경 / 연장 (오늘부터 1개월)": "Change / extend plan (1 month from today)",
  "만료됨": "Expired",
  "프로": "Pro",
  "프리미엄": "Premium",
  "날짜 조정:": "Adjust date:",
  "-30일": "-30d",
  "-7일": "-7d",
  "+30일": "+30d",
  "+7일": "+7d",

  // ── 플랫폼 제어 (PlatformControls) ──
  "🟢 공개": "🟢 Public",
  "✓ 저장됨": "✓ Saved",
  "강제 비공개로 전환": "Force to Private",
  "공개로 전환": "Switch to Public",
  "삭제 실패": "Delete failed",
  "삭제 중…": "Deleting…",
  "삭제(회수)": "Delete (revoke)",
  "이 회원을 플랫폼 관리자로 올릴까요? 전체 권한을 갖게 됩니다.": "Promote this member to platform admin? They'll get full access.",
  "저장 중…": "Saving…",
  "회원 삭제": "Delete Member",
  "관리자": "Admin",
  "삭제됨": "Deleted",

  // ── 결제 수단 (PaymentMethods) ──
  "무통장입금 (계좌이체)": "Bank Transfer",
  "가상계좌": "Virtual Account",
  "카드결제 (PG 연동)": "Card Payment (PG)",
  "자세히": "Details",
  "손님이 위 계좌로 직접 입금. 가장 간단하고 수수료 없음.": "Customer transfers directly to your account. Simplest, no fees.",
  "신용·체크카드 즉시 결제. PG사 가입·심사 필요.": "Instant credit/debit card payment. Requires PG signup & review.",
  "주문마다 1회용 입금 계좌 자동 발급. PG 연동 필요.": "Auto-issues a one-time account per order. Requires PG.",
  "손님이 주문할 때 입력한 계좌번호를 보고 직접 이체합니다.\n\n• 별도 가입·심사 없이 바로 사용\n• 결제 수수료 0원\n• 입금 확인은 사장님이 통장에서 직접 확인 후 발송\n• 입금자명을 주문자명과 같게 안내하면 확인이 편해요\n\n👉 소규모·시작 단계에 가장 추천돼요.": "Customers transfer manually to the account number shown at checkout.\n\n• Use right away — no signup or review\n• Zero payment fees\n• You confirm each deposit in your bankbook before shipping\n• Ask customers to use their order name as the depositor name for easy matching\n\n👉 Best for small or early-stage stores.",
  "토스페이먼츠·나이스페이 등 PG(전자결제대행)사에 가입하면 손님이 카드로 바로 결제할 수 있어요.\n\n• 손님 편의 최고 (즉시 결제·자동 확인)\n• PG사 가입 + 사업자등록 + 심사 필요 (보통 2~5일)\n• 결제 수수료 약 2.5~3.4% 발생\n• 정산은 PG사가 영업일 기준 며칠 뒤 입금\n\n⚠️ 지금은 '안내 노출'만 켜둘 수 있고, 실제 카드결제 연동(본인 PG 계정 연결)은 곧 제공돼요. 그 전까지는 무통장입금과 함께 쓰는 걸 권장해요.": "Sign up with a PG (payment gateway) like Toss Payments or NICEPay so customers can pay by card instantly.\n\n• Best customer convenience (instant payment, auto-confirm)\n• Requires PG signup + business registration + review (usually 2-5 days)\n• Payment fee around 2.5-3.4%\n• PG settles to you a few business days later\n\n⚠️ For now only the info display can be turned on; real card integration (linking your own PG account) is coming soon. Until then, we recommend using it alongside Bank Transfer.",
  "주문할 때마다 손님 전용 1회용 입금 계좌가 자동으로 발급됩니다.\n\n• 입금 확인이 자동 (누가 얼마 넣었는지 자동 매칭)\n• 무통장입금의 '입금자명 확인' 번거로움이 없음\n• PG사 가입·심사 필요 (카드결제와 동일)\n• 발급·입금 건당 소액 수수료\n\n⚠️ 가상계좌도 PG 연동이 있어야 자동 발급돼요. 지금은 '안내 노출'만 켤 수 있고 실제 발급 연동은 곧 제공됩니다.\n\n❓ 카드·가상계좌를 발급받아도 무통장 계좌번호를 함께 노출할지는 위 '무통장입금'을 같이 켜두면 됩니다.": "A one-time account is auto-issued for each customer per order.\n\n• Deposits confirm automatically (auto-matched by who paid how much)\n• No hassle of checking depositor names like bank transfer\n• Requires PG signup & review (same as card)\n• Small fee per issuance/deposit\n\n⚠️ Virtual accounts also need PG integration to auto-issue. For now only the info display can be turned on; real issuance is coming soon.\n\n❓ To also show your bank account number alongside card/virtual account, just keep 'Bank Transfer' above turned on too.",

  // ── 무료 이미지 (ProductImagePicker) ──
  "🖼 무료 이미지 라이브러리": "🖼 Free Image Library",
  "✓ 업로드한 사진이 적용됐어요": "✓ Your uploaded photo is applied",
  "상품 사진이 없어도 무료 이미지 라이브러리(66종)에서 골라 바로 쓸 수 있어요.": "No product photo? Pick from the free image library (66) and use it instantly.",
  "탭하면 바로 적용돼요": "Tap to apply instantly",

  // ── 대문 구성 (SectionEditor) ──
  "✋ 내가 직접 고르기": "✋ Pick manually",
  "＋ 블록 추가": "＋ Add Block",
  "✏️ 탭하여 수정": "✏️ Tap to edit",
  "🔥 '베스트·인기·추천' 태그가 붙은 상품이 자동으로 채워져요.": "Products tagged 'Best/Popular/Featured' fill in automatically.",
  "🎨 기본 대문 구성을 불러오는 중…": "Loading default homepage layout…",
  "🔥 베스트": "🔥 Best",
  "🚫 숨김": "🚫 Hidden",
  "🆕 신상품": "🆕 New Arrivals",
  "✋ 아래 목록에서 이 선반에 넣을 상품을 직접 골라요. (상품을 탭하면 선택/해제)": "Pick products for this shelf from the list below. (Tap a product to select/deselect)",
  "📁 아래에서 고른 카테고리의 상품이 자동으로 채워져요.": "Products from the category you pick below fill in automatically.",
  "🆕 최근 등록한 상품이 자동으로 채워져요. 새 상품을 올리면 알아서 바뀌어요.": "Recently added products fill in automatically. They update as you add new ones.",
  "📁 특정 카테고리": "📁 Specific Category",
  "👁 표시": "👁 Shown",
  "블록이 하나도 없으면 기본 진열(신상·베스트·전체)이 자동으로 보입니다.": "If there are no blocks, the default layout (New, Best, All) shows automatically.",
  "고른 분류 상품": "Picked category products",
  "기획전 배너": "Promo Banner",
  "기획전 제목": "Promo Title",
  "내용을 입력하세요.": "Enter content.",
  "드래그로 이동": "Drag to reorder",
  "베스트": "Best",
  "변경사항 저장": "Save Changes",
  "보러가기": "View",
  "보이기": "Show",
  "상품 선반": "Product Shelf",
  "상품을 직접 선택": "Select products manually",
  "숨기기": "Hide",
  "신상품": "New Arrivals",
  "아래에서 상품을 직접 골라주세요.": "Pick products below.",
  "이 블록을 삭제할까요?": "Delete this block?",
  "인기 상품 자동": "Popular products (auto)",
  "저장됨": "Saved",
  "전체 상품 그리드": "All Products Grid",
  "지금 보기": "View now",
  "직접 선택": "Manual pick",
  "최근 올린 상품 자동": "Recent products (auto)",
  "텍스트": "Text",
  "표시할 상품이 없어요.": "No products to show.",
  "(선택하세요)": "(Select)",
  "(선택)": "(optional)",
  "부제를 입력하세요": "Enter a subtitle",
};
