/* ════════════════════════════════════════════════
   dict.ts — 대시보드(쇼핑몰 관리) 한글 → 영어 사전
   런타임 번역 레이어(DashTranslator)가 영어 모드일 때
   화면의 한글 텍스트를 이 사전으로 치환한다.
   · 키 = 화면에 그대로 보이는 한글(트림 기준 정확 일치)
   · 사전에 없으면 한글 그대로 둠(안 깨짐) → 점진적으로 채운다
════════════════════════════════════════════════ */
export const DICT: Record<string, string> = {
  // ── 사이드바 / 네비 ──
  "대시보드": "Dashboard",
  "쇼핑몰": "Stores",
  "상품": "Products",
  "주문": "Orders",
  "고객": "Customers",
  "리뷰": "Reviews",
  "문의": "Inquiries",
  "재입고": "Restock",
  "알림": "Notifications",
  "분석": "Analytics",
  "요금제": "Pricing",
  "계정 설정": "Account Settings",
  "설정": "Settings",
  "BUILD": "BUILD",
  "OPERATE": "OPERATE",
  "SYSTEM": "SYSTEM",
  "관리": "Manage",
  "메뉴": "Menu",
  "로그아웃": "Log out",
  "로그인": "Log in",
  "회원가입": "Sign up",
  "무료로 시작": "Start free",
  "최고관리자": "Super Admin",
  "온라인": "Online",
  "창업자": "Founder",
  "👑 플랫폼 관리자": "👑 Platform Admin",
  "🏪 창업자": "🏪 Founder",
  "👑 운영자 시크릿 보기": "👑 Admin secret view",
  "← 운영자로 나가기": "← Exit to admin",
  "비로그인 (둘러보기)": "Not logged in (browsing)",
  "📅 이용 기간": "📅 Subscription period",
  "사용 기간 만료": "Subscription expired",
  "연장 문의가 필요해요": "Renewal inquiry needed",

  // ── 공통 버튼/동작 ──
  "저장": "Save",
  "저장하기": "Save",
  "취소": "Cancel",
  "삭제": "Delete",
  "수정": "Edit",
  "편집": "Edit",
  "추가": "Add",
  "닫기": "Close",
  "확인": "Confirm",
  "적용": "Apply",
  "적용하기": "Apply",
  "등록": "Register",
  "등록하기": "Register",
  "생성": "Create",
  "생성하기": "Create",
  "변경": "Change",
  "초기화": "Reset",
  "복사": "Copy",
  "복사됨": "Copied",
  "미리보기": "Preview",
  "더보기": "More",
  "전체": "All",
  "검색": "Search",
  "필터": "Filter",
  "정렬": "Sort",
  "다운로드": "Download",
  "업로드": "Upload",
  "이전": "Previous",
  "다음": "Next",
  "처음으로": "Home",
  "뒤로": "Back",

  // ── 대시보드 개요 ──
  "오늘 매출": "Today's Sales",
  "이번 달 매출": "This Month's Sales",
  "총 주문": "Total Orders",
  "신규 주문": "New Orders",
  "총 매출": "Total Sales",
  "방문자": "Visitors",
  "상품 수": "Products",
  "고객 수": "Customers",
  "최근 주문": "Recent Orders",
  "주문이 없어요": "No orders yet",
  "환영합니다": "Welcome",
  "빠른 시작": "Quick Start",
  "쇼핑몰 만들기": "Create a store",
  "상품 등록": "Add a product",

  // ── 상품 ──
  "상품 관리": "Product Management",
  "상품 추가": "Add Product",
  "새 상품": "New Product",
  "상품명": "Product Name",
  "가격": "Price",
  "정가": "List Price",
  "할인가": "Sale Price",
  "재고": "Stock",
  "카테고리": "Category",
  "상품 설명": "Product Description",
  "이미지": "Image",
  "대표 이미지": "Main Image",
  "옵션": "Options",
  "품절": "Sold Out",
  "판매중": "On Sale",
  "숨김": "Hidden",
  "진열": "Display",
  "상품이 없어요": "No products yet",
  "첫 상품을 등록해 보세요": "Add your first product",

  // ── 주문 ──
  "주문 관리": "Order Management",
  "주문번호": "Order No.",
  "주문일": "Order Date",
  "주문자": "Customer",
  "주문 상태": "Order Status",
  "결제금액": "Total",
  "배송지": "Shipping Address",
  "송장번호": "Tracking No.",
  "신규": "New",
  "처리중": "Processing",
  "배송중": "Shipping",
  "배송완료": "Delivered",
  "완료": "Completed",
  "환불": "Refunded",
  "주문이 들어오면 여기에 표시돼요": "Orders will appear here",

  // ── 고객 ──
  "고객 관리": "Customer Management",
  "이름": "Name",
  "이메일": "Email",
  "전화번호": "Phone",
  "가입일": "Joined",
  "총 구매액": "Total Spent",
  "등급": "Grade",
  "적립금": "Points",
  "회원": "Member",
  "고객이 없어요": "No customers yet",

  // ── 설정 / 계정 ──
  "계정 정보": "Account Info",
  "비밀번호": "Password",
  "비밀번호 변경": "Change Password",
  "현재 비밀번호": "Current Password",
  "새 비밀번호": "New Password",
  "비밀번호 확인": "Confirm Password",
  "저장되었습니다": "Saved",
  "변경되었습니다": "Changed",
  "회원 탈퇴": "Delete Account",

  // ── 요금제(보강) ──
  "현재 플랜": "Current Plan",
  "무제한": "Unlimited",
  "무료": "Free",
  "업그레이드": "Upgrade",
  "업그레이드 문의": "Upgrade",

  // ── 상태/공통 메시지 ──
  "로딩 중...": "Loading...",
  "불러오는 중...": "Loading...",
  "저장 중...": "Saving...",
  "처리 중...": "Processing...",
  "오류가 발생했어요": "An error occurred",
  "다시 시도해 주세요": "Please try again",
  "준비 중인 기능이에요": "Coming soon",
  "필수 입력이에요": "Required",
  "필수": "Required",
  "선택": "Optional",
  "사용함": "Enabled",
  "사용 안 함": "Disabled",
  "켜기": "On",
  "끄기": "Off",
  "예": "Yes",
  "아니오": "No",

  // ── 대시보드 개요 (page) ──
  "내 쇼핑몰": "My Stores",
  "현황 통계": "Overview",
  "사용 가능 스킨": "Available Skins",
  "운영 쇼핑몰": "Active Stores",
  "전체 상품": "Total Products",
  "전체 상품 보기": "View all products",
  "빠른 작업": "Quick Actions",
  "스튜디오에서 스킨 고르고 생성": "Pick a skin in Studio and create",
  "최근 쇼핑몰": "Recent Stores",
  "만든 매장 목록·관리": "Your stores",
  "모든 쇼핑몰을 여기서 만들고 · 수정하고 · 관리하세요": "Create, edit and manage all your stores here",
  "주소 (수정 가능)": "Address (editable)",
  "🧾 새 주문 (신규)": "🧾 New Orders",
  "📦 전체 주문": "📦 Total Orders",
  "💰 총 매출 (취소 제외)": "💰 Total Sales (excl. cancelled)",
  "구독 사용 기간": "Subscription period",
  "일 남음": "days left",
  "까지": "until",

  // ── 주문 페이지 ──
  "🧾 주문": "🧾 Orders",
  "고객 주문을 한 곳에서 확인하고 상태를 관리하세요.": "View and manage all customer orders in one place.",
  "새 주문": "New Orders",
  "전체 주문": "Total Orders",
  "아직 주문이 없어요": "No orders yet",
  "주문 금액(취소 제외)": "Revenue (excl. cancelled)",
  "배송비": "Shipping",
  " (배송비 포함)": " (incl. shipping)",
  "(배송비 포함)": "(incl. shipping)",

  // ── 고객 페이지 ──
  "👤 고객": "👤 Customers",
  "💰 회원 적립금": "💰 Member Points",
  "주문한 고객을 한눈에 보고, 단골을 찾아보세요.": "See who ordered and find your regulars.",
  "전체 고객": "Total Customers",
  "재구매 고객": "Repeat Customers",
  "누적 구매액": "Total Spent",
  "구매액": "Spent",
  "연락처": "Contact",
  "최근": "Recent",
  "아직 고객이 없어요": "No customers yet",

  // ── 설정 페이지 ──
  "관리자 · 컨트롤타워": "Admin · Control Tower",
  "관리자 계정": "Admin Account",
  "관리자 계정과 비밀번호를 관리하세요": "Manage your admin account and password",
  "관리자 로그인": "Admin Login",
  "비밀번호를 바꾸려면 먼저 로그인하세요.": "Log in first to change your password.",
  "로그인한 관리자 계정의 비밀번호를 바꿉니다.": "Change the password for the logged-in admin account.",
  "새 비밀번호 확인": "Confirm New Password",
  "🔒 계정 보안 팁": "🔒 Account Security Tips",
  "💬 도움이 필요하세요?": "💬 Need help?",
  "⚡ 빠른 이동": "⚡ Quick Links",
  "📈 분석": "📈 Analytics",
  "🏬 쇼핑몰": "🏬 Stores",
  "💎 요금제": "💎 Pricing",
  "온봇": "OnBot",
  "요금제 페이지": "Pricing page",
  "6자 이상": "6+ characters",
  "8자 이상": "8+ characters",
  "다시 입력": "Re-enter",
  "같은 비밀번호": "Same password",

  // ── 몰 관리 (dashboard/[id]) 섹션 ──
  "🔎 검색 노출 (SEO)": "🔎 Search Visibility (SEO)",
  "💳 결제 설정": "💳 Payment Settings",
  "🌐 내 도메인 연결": "🌐 Connect My Domain",
  "🧩 대문 구성": "🧩 Homepage Layout",
  "🎨 디자인": "🎨 Design",
  "🚚 배송비": "🚚 Shipping Fee",
  "🎨 상단 꾸미기": "🎨 Header Styling",
  "📦 상품": "📦 Products",
  "🗣️ 손님 후기·문의": "🗣️ Reviews & Inquiries",
  "💬 쇼핑몰 챗봇 (자주 묻는 질문)": "💬 Store Chatbot (FAQ)",
  "🎉 이벤트 팝업·띠배너": "🎉 Event Popup & Banner",
  "💰 적립금": "💰 Points",
  "🏷️ 카테고리": "🏷️ Categories",
  "🎟️ 쿠폰": "🎟️ Coupons",
  "💎 회원 등급": "💎 Member Grades",
  "⭐ 구매 후기 (리뷰)": "⭐ Reviews",
  "💬 상품 문의 (Q&A)": "💬 Product Q&A",
  "🏢 사업자 정보": "🏢 Business Info",
  "💳 카드결제 연결 (PG)": "💳 Card Payment (PG)",
  "🟢 발행됨": "🟢 Published",
  "🚀 발행하기": "🚀 Publish",
  "⚪ 비공개": "⚪ Private",
  "비공개로 전환": "Switch to Private",
  "발행해야 고객에게 보입니다": "Must publish to be visible to customers",
  "고객이 접속할 수 있어요": "Customers can access it",
  "👑 운영자 모드 — 다른 회원의 쇼핑몰을 관리 중입니다. 변경 시 즉시 적용돼요.": "👑 Admin mode — managing another member's store. Changes apply immediately.",
  "결제 설정 저장": "Save Payment Settings",
  "배송비 설정 저장": "Save Shipping Settings",
  "사업자 정보 저장": "Save Business Info",
  "이벤트 설정 저장": "Save Event Settings",
  "적립금 설정 저장": "Save Points Settings",
  "챗봇 설정 저장": "Save Chatbot Settings",
  "고객 주문 관리": "Customer Order Management",
  "고객센터 전화": "Support Phone",
  "대표자명": "Representative",
  "사업자등록번호": "Business Reg. No.",
  "상호 (상점·법인명)": "Business Name",
  "내 도메인(mybrand.com)을 이 쇼핑몰에 연결할 수 있어요.": "Connect your own domain (mybrand.com) to this store.",
  "누적 구매액에 따라 VIP 등급을 나누고 등급별 할인을 줄 수 있어요.": "Split VIP grades by total spend and give per-grade discounts.",
  "주문 완료 시 손님에게 적립금을 쌓아 단골을 만들 수 있어요.": "Give points on completed orders to build loyal customers.",

  // ── 상품 폼 (ProductForm) ──
  "🔍 미리보기 · 실시간": "🔍 Preview · Live",
  "가격(원) *": "Price (KRW) *",
  "상품명 *": "Product Name *",
  "상품명이 여기에 표시돼요": "Product name shows here",
  "상품 사진 (선택 — 없으면 이모지 사용)": "Product Photo (optional — emoji if none)",
  "옵션 (색상·사이즈 등)": "Options (color, size, etc.)",
  "이모지(사진 없을 때 대체)": "Emoji (fallback when no photo)",
  "재고 수량(비우면 무제한)": "Stock (blank = unlimited)",
  "정가 (할인 전 가격·선택)": "List Price (before discount, optional)",
  "태그(NEW·BEST 등)": "Tag (NEW, BEST, etc.)",
  "브랜드": "Brand",
  "설명": "Description",
  "리빙": "Living",
  "뷰티": "Beauty",
  "테크": "Tech",
  "패션": "Fashion",
  "액세서리": "Accessories",
  "식품": "Food",
  "농산물": "Produce",
  "수산물": "Seafood",
  "축산물": "Meat",
  "베이커리": "Bakery",
  "가공·반찬": "Processed",
  "베이직": "Basic",

  // ── 분석 페이지 ──
  "🏆 인기 상품 (실제 판매 수량)": "🏆 Top Products (units sold)",
  "🧾 주문 수": "🧾 Order Count",
  "📊 최근 14일 매출 추이": "📊 Sales (last 14 days)",
  "📦 판매 수량": "📦 Units Sold",
  "📊 평균 주문액": "📊 Avg Order Value",
  "매출 추이·상품별 판매·카테고리 분포 등 분석 리포트를 볼 수 있어요.": "View reports: sales trend, per-product sales, category mix, and more.",
  "매출·상품·고객 통계를 한눈에 볼 수 있어요.": "See sales, product, and customer stats at a glance.",
  "매출과 운영 현황을 한눈에": "Sales and operations at a glance",
  "데이터가 없어요.": "No data yet.",
  "스킨 분포": "Skin Distribution",
  "카테고리 분포": "Category Distribution",
  "합계": "Total",
  "아직 판매된 상품이 없어요. 주문이 들어오면 표시돼요.": "No products sold yet. They'll show when orders come in.",
  "최근 14일 매출이 없어요. 주문(완료/접수)이 들어오면 일별로 표시돼요.": "No sales in the last 14 days. Daily sales appear as orders come in.",

  // ── 플랫폼 관리 (platform) ──
  "🧾 새 주문": "🧾 New Orders",
  "💰 전체 거래액": "💰 Total Revenue",
  " (만료)": " (expired)",
  "모든 회원과 쇼핑몰·매출을 총괄하고 직접 제어합니다": "Oversee and control all members, stores, and sales",
  "역할": "Role",
  "이용 만료": "Expiry",
  "전체 관리": "Platform",
  "전체 쇼핑몰": "Total Stores",
  "전체 회원": "Total Members",

  // ── 매장 목록 (stores) ──
  "＋ 새 쇼핑몰 만들기": "＋ Create New Store",
  "매장을 만들고 관리하세요": "Create and manage your stores",

  // ── 쿠폰 (CouponManager) ──
  "🎟️ 새 쿠폰 발급": "🎟️ Issue New Coupon",
  "⚪ 비활성": "⚪ Inactive",
  "🟢 활성": "🟢 Active",
  "(원)": "(KRW)",
  "만료": "Expired",
  "발급 중…": "Issuing…",
  "발급에 실패했어요.": "Failed to issue.",
  "쿠폰 발급": "Issue Coupon",
  "한도 소진": "Limit reached",
  "금액(원) 할인": "Amount (KRW) off",
  "만료일 (비우면 무기한)": "Expiry (blank = no expiry)",
  "사용 한도 (비우면 무제한)": "Usage limit (blank = unlimited)",
  "아직 발급한 쿠폰이 없어요.": "No coupons issued yet.",
  "최소 주문금액 (원)": "Min. order (KRW)",
  "쿠폰 코드": "Coupon Code",
  "퍼센트(%) 할인": "Percent (%) off",
  "할인 종류": "Discount Type",

  // ── 회원 등급 (StoreGradeManager) ──
  "✨ 기본 등급 채우기 (일반·실버·골드·VIP)": "✨ Fill default grades (Basic·Silver·Gold·VIP)",
  "＋ 등급 추가": "＋ Add Grade",
  "등급 추가": "Add Grade",
  "기본 등급 채우기 실패": "Failed to fill default grades",
  "꺼짐 — 등급 미사용": "Off — grades disabled",
  "수정 실패": "Update failed",
  "추가 실패": "Add failed",
  "이 등급을 삭제할까요?": "Delete this grade?",
  "켜짐 — 구매액에 따라 등급 할인이 적용돼요": "On — grade discounts apply by total spend",
  "% 할인": "% off",
  "누적": "Total",
  "아직 등급이 없어요. 위에서 추가하거나 기본 등급을 채워보세요.": "No grades yet. Add one above or fill defaults.",

  // ── 적립금 (MemberPoints) ──
  "금액을 입력해 주세요.": "Please enter an amount.",
  "쿠폰을 선택해 주세요.": "Please select a coupon.",
  "쿠폰을 발급했어요 ✓ (회원 쿠폰함에 담김)": "Coupon issued ✓ (added to member's coupon box)",
  "사용": "Use",
  "실패": "Failed",
  "처리 실패": "Failed",
  "원": "KRW",
  "적립": "Earn",
  "지급": "Grant",
  "차감": "Deduct",
  "회수": "Revoke",
  "불러오는 중…": "Loading…",
  "아직 적립금 변동 내역이 없어요.": "No points history yet.",
  "적립금 내역": "Points History",
  "적립금 지급 / 차감": "Grant / Deduct Points",
  "쿠폰 선택…": "Select coupon…",

  // ── 배송비 (ShippingSettings) ──
  "기준액": "Threshold",
  "꺼짐 — 배송비 없이(무료) 받아요": "Off — free shipping (no fee)",
  "켜짐 — 주문 시 배송비가 더해져요": "On — shipping fee added at checkout",
  "기본 배송비": "Base Shipping Fee",
  "도서산간 추가 배송비": "Remote Area Surcharge",
  "무료배송": "Free Shipping",
  "무료배송 기준액": "Free Shipping Threshold",
  "주문마다 더해질 배송비예요.": "Shipping fee added to each order.",
  "제주·도서산간 주문이면 더 받을 금액 (0이면 안 받음).": "Extra for Jeju/remote areas (0 = none).",

  // ── 이벤트 팝업·배너 (PromoSettings) ──
  "📢 상단 띠배너": "📢 Top Banner",
  "🪟 진입 팝업": "🪟 Entry Popup",
  "꺼짐": "Off",
  "켜짐 — 대문 맨 위 얇은 줄에 표시": "On — shows as a thin bar at the top",
  "켜짐 — 손님 접속 시 가운데 모달로 표시": "On — shows as a center modal on visit",
  "글자색": "Text Color",
  "내용": "Content",
  "배경색": "Background Color",
  "배너 문구": "Banner Text",
  "버튼 링크": "Button Link",
  "버튼 문구 (선택)": "Button Text (optional)",
  "이미지 URL (선택)": "Image URL (optional)",
  "제목": "Title",
  "클릭 링크 (선택 · URL)": "Click Link (optional · URL)",

  // ── 리뷰 / 문의 / 재입고 / 알림 페이지 ──
  "⭐ 리뷰": "⭐ Reviews",
  "답글 단 리뷰": "Replied",
  "손님이 남긴 후기를 확인하고 답글을 달아보세요.": "Check customer reviews and reply to them.",
  "아직 리뷰가 없어요": "No reviews yet",
  "전체 리뷰": "Total Reviews",
  "평균 별점": "Avg Rating",
  "💬 상품 문의": "💬 Product Inquiries",
  "답변 대기": "Pending",
  "답변 완료": "Answered",
  "손님이 상품에 남긴 질문을 확인하고 답변을 달아보세요.": "Check and answer customer questions on products.",
  "아직 문의가 없어요": "No inquiries yet",
  "전체 문의": "Total Inquiries",
  "🔔 재입고 알림 신청": "🔔 Restock Alerts",
  "품절 상품에 손님의 재입고 알림을 받고, 입고되면 한 번에 알려줄 수 있어요.": "Collect restock requests on sold-out items and notify customers at once.",
  "로그인하면 신청 목록을 볼 수 있어요.": "Log in to see the request list.",
  "아직 재입고 신청이 없어요": "No restock requests yet",
  "알림 대기": "Awaiting",
  "전체 신청": "Total Requests",
  "🔔 알림": "🔔 Notifications",
  "새 주문·리뷰가 들어오면 여기에서 바로 확인하세요.": "Check new orders and reviews here as they arrive.",
};
