/* ════════════════════════════════════════════════
   dict.ts — 대시보드(쇼핑몰 관리) 한글 → 영어 사전
   런타임 번역 레이어(DashTranslator)가 영어 모드일 때
   화면의 한글 텍스트를 이 사전으로 치환한다.
   · 키 = 화면에 그대로 보이는 한글(트림 기준 정확 일치)
   · 사전에 없으면 한글 그대로 둠(안 깨짐) → 점진적으로 채운다
════════════════════════════════════════════════ */
export const DICT: Record<string, string> = {
  // ── 사이드바 / 네비 ──
  "대시보드": "Dashboard",
  "쇼핑몰": "Stores",
  "상품": "Products",
  "주문": "Orders",
  "고객": "Customers",
  "리뷰": "Reviews",
  "문의": "Inquiries",
  "재입고": "Restock",
  "알림": "Notifications",
  "분석": "Analytics",
  "요금제": "Pricing",
  "계정 설정": "Account Settings",
  "설정": "Settings",
  "BUILD": "BUILD",
  "OPERATE": "OPERATE",
  "SYSTEM": "SYSTEM",
  "관리": "Manage",
  "메뉴": "Menu",
  "로그아웃": "Log out",
  "로그인": "Log in",
  "회원가입": "Sign up",
  "무료로 시작": "Start free",
  "최고관리자": "Super Admin",
  "온라인": "Online",
  "창업자": "Founder",
  "👑 플랫폼 관리자": "👑 Platform Admin",
  "🏪 창업자": "🏪 Founder",
  "👑 운영자 시크릿 보기": "👑 Admin secret view",
  "← 운영자로 나가기": "← Exit to admin",
  "비로그인 (둘러보기)": "Not logged in (browsing)",
  "📅 이용 기간": "📅 Subscription period",
  "사용 기간 만료": "Subscription expired",
  "연장 문의가 필요해요": "Renewal inquiry needed",

  // ── 공통 버튼/동작 ──
  "저장": "Save",
  "저장하기": "Save",
  "취소": "Cancel",
  "삭제": "Delete",
  "수정": "Edit",
  "편집": "Edit",
  "추가": "Add",
  "닫기": "Close",
  "확인": "Confirm",
  "적용": "Apply",
  "적용하기": "Apply",
  "등록": "Register",
  "등록하기": "Register",
  "생성": "Create",
  "생성하기": "Create",
  "변경": "Change",
  "초기화": "Reset",
  "복사": "Copy",
  "복사됨": "Copied",
  "미리보기": "Preview",
  "더보기": "More",
  "전체": "All",
  "검색": "Search",
  "필터": "Filter",
  "정렬": "Sort",
  "다운로드": "Download",
  "업로드": "Upload",
  "이전": "Previous",
  "다음": "Next",
  "처음으로": "Home",
  "뒤로": "Back",

  // ── 대시보드 개요 ──
  "오늘 매출": "Today's Sales",
  "이번 달 매출": "This Month's Sales",
  "총 주문": "Total Orders",
  "신규 주문": "New Orders",
  "총 매출": "Total Sales",
  "방문자": "Visitors",
  "상품 수": "Products",
  "고객 수": "Customers",
  "최근 주문": "Recent Orders",
  "주문이 없어요": "No orders yet",
  "환영합니다": "Welcome",
  "빠른 시작": "Quick Start",
  "쇼핑몰 만들기": "Create a store",
  "상품 등록": "Add a product",

  // ── 상품 ──
  "상품 관리": "Product Management",
  "상품 추가": "Add Product",
  "새 상품": "New Product",
  "상품명": "Product Name",
  "가격": "Price",
  "정가": "List Price",
  "할인가": "Sale Price",
  "재고": "Stock",
  "카테고리": "Category",
  "상품 설명": "Product Description",
  "이미지": "Image",
  "대표 이미지": "Main Image",
  "옵션": "Options",
  "품절": "Sold Out",
  "판매중": "On Sale",
  "숨김": "Hidden",
  "진열": "Display",
  "상품이 없어요": "No products yet",
  "첫 상품을 등록해 보세요": "Add your first product",

  // ── 주문 ──
  "주문 관리": "Order Management",
  "주문번호": "Order No.",
  "주문일": "Order Date",
  "주문자": "Customer",
  "주문 상태": "Order Status",
  "결제금액": "Total",
  "배송지": "Shipping Address",
  "송장번호": "Tracking No.",
  "신규": "New",
  "처리중": "Processing",
  "배송중": "Shipping",
  "배송완료": "Delivered",
  "완료": "Completed",
  "환불": "Refunded",
  "주문이 들어오면 여기에 표시돼요": "Orders will appear here",

  // ── 고객 ──
  "고객 관리": "Customer Management",
  "이름": "Name",
  "이메일": "Email",
  "전화번호": "Phone",
  "가입일": "Joined",
  "총 구매액": "Total Spent",
  "등급": "Grade",
  "적립금": "Points",
  "회원": "Member",
  "고객이 없어요": "No customers yet",

  // ── 설정 / 계정 ──
  "계정 정보": "Account Info",
  "비밀번호": "Password",
  "비밀번호 변경": "Change Password",
  "현재 비밀번호": "Current Password",
  "새 비밀번호": "New Password",
  "비밀번호 확인": "Confirm Password",
  "저장되었습니다": "Saved",
  "변경되었습니다": "Changed",
  "회원 탈퇴": "Delete Account",

  // ── 요금제(보강) ──
  "현재 플랜": "Current Plan",
  "무제한": "Unlimited",
  "무료": "Free",
  "업그레이드": "Upgrade",
  "업그레이드 문의": "Upgrade",

  // ── 상태/공통 메시지 ──
  "로딩 중...": "Loading...",
  "불러오는 중...": "Loading...",
  "저장 중...": "Saving...",
  "처리 중...": "Processing...",
  "오류가 발생했어요": "An error occurred",
  "다시 시도해 주세요": "Please try again",
  "준비 중인 기능이에요": "Coming soon",
  "필수 입력이에요": "Required",
  "필수": "Required",
  "선택": "Optional",
  "사용함": "Enabled",
  "사용 안 함": "Disabled",
  "켜기": "On",
  "끄기": "Off",
  "예": "Yes",
  "아니오": "No",
};
