// 무료 상품 이미지 라이브러리 (온종일 AI 제품 이미지)
// public/landing/img/ 에 이미 배포돼 있어 업로드 없이 URL로 바로 사용.
// 회원이 상품 사진이 없어도 에디터에서 골라 쓸 수 있는 공용 소재.

export type StockImage = { src: string; cat: string; group: "식품" | "라이프스타일" };

export const STOCK_IMAGES: StockImage[] = [
  { src: "/landing/img/food/bakery_baguette.webp", cat: "베이커리", group: "식품" },
  { src: "/landing/img/food/bakery_bread.webp", cat: "베이커리", group: "식품" },
  { src: "/landing/img/food/bakery_cookie.webp", cat: "베이커리", group: "식품" },
  { src: "/landing/img/food/bakery_croissant.webp", cat: "베이커리", group: "식품" },
  { src: "/landing/img/food/bakery_cupcake.webp", cat: "베이커리", group: "식품" },
  { src: "/landing/img/food/bakery_pretzel.webp", cat: "베이커리", group: "식품" },
  { src: "/landing/img/food/banchan_anchovy.webp", cat: "반찬", group: "식품" },
  { src: "/landing/img/food/banchan_eomuk.webp", cat: "반찬", group: "식품" },
  { src: "/landing/img/food/banchan_geotjeori.webp", cat: "반찬", group: "식품" },
  { src: "/landing/img/food/banchan_jangjorim.webp", cat: "반찬", group: "식품" },
  { src: "/landing/img/food/banchan_riceball.webp", cat: "반찬", group: "식품" },
  { src: "/landing/img/food/banchan_stew.webp", cat: "반찬", group: "식품" },
  { src: "/landing/img/food/dairy_butter.webp", cat: "유제품", group: "식품" },
  { src: "/landing/img/food/dairy_cheese.webp", cat: "유제품", group: "식품" },
  { src: "/landing/img/food/dairy_icecream.webp", cat: "유제품", group: "식품" },
  { src: "/landing/img/food/dairy_milk.webp", cat: "유제품", group: "식품" },
  { src: "/landing/img/food/dairy_pudding.webp", cat: "유제품", group: "식품" },
  { src: "/landing/img/food/dairy_yogurt.webp", cat: "유제품", group: "식품" },
  { src: "/landing/img/food/food_egg.webp", cat: "기타식품", group: "식품" },
  { src: "/landing/img/food/food_honey.webp", cat: "기타식품", group: "식품" },
  { src: "/landing/img/food/fruit_apple.webp", cat: "과일", group: "식품" },
  { src: "/landing/img/food/fruit_grape.webp", cat: "과일", group: "식품" },
  { src: "/landing/img/food/fruit_mango.webp", cat: "과일", group: "식품" },
  { src: "/landing/img/food/fruit_peach.webp", cat: "과일", group: "식품" },
  { src: "/landing/img/food/fruit_strawberry.webp", cat: "과일", group: "식품" },
  { src: "/landing/img/food/fruit_tangerine.webp", cat: "과일", group: "식품" },
  { src: "/landing/img/food/gourmet_cheeseplatter.webp", cat: "가공·선물", group: "식품" },
  { src: "/landing/img/food/gourmet_chocolate.webp", cat: "가공·선물", group: "식품" },
  { src: "/landing/img/food/gourmet_giftset.webp", cat: "가공·선물", group: "식품" },
  { src: "/landing/img/food/gourmet_oliveoil.webp", cat: "가공·선물", group: "식품" },
  { src: "/landing/img/food/gourmet_teaset.webp", cat: "가공·선물", group: "식품" },
  { src: "/landing/img/food/gourmet_wine.webp", cat: "가공·선물", group: "식품" },
  { src: "/landing/img/food/meat_bacon.webp", cat: "정육", group: "식품" },
  { src: "/landing/img/food/meat_beef.webp", cat: "정육", group: "식품" },
  { src: "/landing/img/food/meat_chicken.webp", cat: "정육", group: "식품" },
  { src: "/landing/img/food/meat_porkbelly.webp", cat: "정육", group: "식품" },
  { src: "/landing/img/food/meat_sausage.webp", cat: "정육", group: "식품" },
  { src: "/landing/img/food/meat_striploin.webp", cat: "정육", group: "식품" },
  { src: "/landing/img/food/produce_broccoli.webp", cat: "채소", group: "식품" },
  { src: "/landing/img/food/produce_carrot.webp", cat: "채소", group: "식품" },
  { src: "/landing/img/food/produce_garlic.webp", cat: "채소", group: "식품" },
  { src: "/landing/img/food/produce_mushroom.webp", cat: "채소", group: "식품" },
  { src: "/landing/img/food/produce_spinach.webp", cat: "채소", group: "식품" },
  { src: "/landing/img/food/produce_ssam.webp", cat: "채소", group: "식품" },
  { src: "/landing/img/food/seafood_driedshrimp.webp", cat: "수산", group: "식품" },
  { src: "/landing/img/food/seafood_hairtail.webp", cat: "수산", group: "식품" },
  { src: "/landing/img/food/seafood_myeongnan.webp", cat: "수산", group: "식품" },
  { src: "/landing/img/food/seafood_oyster.webp", cat: "수산", group: "식품" },
  { src: "/landing/img/food/seafood_prawn.webp", cat: "수산", group: "식품" },
  { src: "/landing/img/food/seafood_squid.webp", cat: "수산", group: "식품" },
  { src: "/landing/img/food/traditional_doenjang.webp", cat: "전통·장류", group: "식품" },
  { src: "/landing/img/food/traditional_giftset.webp", cat: "전통·장류", group: "식품" },
  { src: "/landing/img/food/traditional_gochujang.webp", cat: "전통·장류", group: "식품" },
  { src: "/landing/img/food/traditional_kimchi.webp", cat: "전통·장류", group: "식품" },
  { src: "/landing/img/food/traditional_makgeolli.webp", cat: "전통·장류", group: "식품" },
  { src: "/landing/img/food/traditional_tea.webp", cat: "전통·장류", group: "식품" },
  { src: "/landing/img/products/candle.webp", cat: "캔들", group: "라이프스타일" },
  { src: "/landing/img/products/cap.webp", cat: "캡모자", group: "라이프스타일" },
  { src: "/landing/img/products/earbuds.webp", cat: "무선이어폰", group: "라이프스타일" },
  { src: "/landing/img/products/mug.webp", cat: "머그컵", group: "라이프스타일" },
  { src: "/landing/img/products/plant.webp", cat: "식물", group: "라이프스타일" },
  { src: "/landing/img/products/serum.webp", cat: "세럼", group: "라이프스타일" },
  { src: "/landing/img/products/sneaker.webp", cat: "스니커즈", group: "라이프스타일" },
  { src: "/landing/img/products/sunglasses.webp", cat: "선글라스", group: "라이프스타일" },
  { src: "/landing/img/products/tote.webp", cat: "토트백", group: "라이프스타일" },
  { src: "/landing/img/products/watch.webp", cat: "손목시계", group: "라이프스타일" },
  { src: "/landing/img/products/knit.webp", cat: "니트", group: "라이프스타일" },
  { src: "/landing/img/products/coat.webp", cat: "코트", group: "라이프스타일" },
  { src: "/landing/img/products/perfume.webp", cat: "향수", group: "라이프스타일" },
  { src: "/landing/img/products/lipstick.webp", cat: "립스틱", group: "라이프스타일" },
  { src: "/landing/img/products/shoulderbag.webp", cat: "숄더백", group: "라이프스타일" },
  { src: "/landing/img/products/handcream.webp", cat: "핸드크림", group: "라이프스타일" },
  { src: "/landing/img/products/diffuser.webp", cat: "디퓨저", group: "라이프스타일" },
  { src: "/landing/img/products/coffeebean.webp", cat: "원두커피", group: "라이프스타일" },
  { src: "/landing/img/products/necklace.webp", cat: "목걸이", group: "라이프스타일" },
  { src: "/landing/img/products/tumbler.webp", cat: "텀블러", group: "라이프스타일" },
  { src: "/landing/img/products/moodlamp.webp", cat: "무드등", group: "라이프스타일" },
  { src: "/landing/img/products/backpack.webp", cat: "백팩", group: "라이프스타일" },
  { src: "/landing/img/products/bouquet.webp", cat: "꽃다발", group: "라이프스타일" },
  { src: "/landing/img/products/wallet.webp", cat: "지갑", group: "라이프스타일" },
  { src: "/landing/img/products/earring.webp", cat: "귀걸이", group: "라이프스타일" },
  { src: "/landing/img/products/notebook.webp", cat: "노트", group: "라이프스타일" },];

export const STOCK_GROUPS = ["전체", "식품", "라이프스타일"] as const;
